name: Deploy to ECS Fargate

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build, Push and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_URI="346871994774.dkr.ecr.us-east-1.amazonaws.com/freelancingapi-app:latest"
          docker build -t freelancingapi-app .
          docker tag freelancingapi-app:latest $IMAGE_URI
          docker push $IMAGE_URI

      - name: Render New Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs_task_definition.json
          container-name: FreelancingAPIContainer-3
          image: 346871994774.dkr.ecr.us-east-1.amazonaws.com/freelancingapi-app:latest

      - name: Register ECS task definition
        id: register-task-def
        uses: aws-actions/amazon-ecs-register-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}

      - name: Deploy ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.register-task-def.outputs.task-definition-arn }}
          service: FreelancingAPIService
          cluster: FreelancingAPICluster
          wait-for-service-stability: true
